-- Extra fields for richer event metadata
ALTER TABLE "Show"
ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "doorsOpenTime" TEXT,
ADD COLUMN IF NOT EXISTS "ageGuidance" TEXT,
ADD COLUMN IF NOT EXISTS "endTimeNote" TEXT,
ADD COLUMN IF NOT EXISTS "eventType" TEXT,
ADD COLUMN IF NOT EXISTS "eventCategory" TEXT,
ADD COLUMN IF NOT EXISTS "additionalImages" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "accessibility" JSONB;
