ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "storefrontId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingEmail" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingPhone" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "shippingAddressJson" JSONB;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "containsProducts" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "containsTickets" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "productSubtotalPence" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "ticketSubtotalPence" INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS "Order_storefrontId_idx" ON "Order"("storefrontId");

ALTER TABLE "Order"
  ADD CONSTRAINT "Order_storefrontId_fkey"
  FOREIGN KEY ("storefrontId") REFERENCES "Storefront"("id") ON DELETE SET NULL ON UPDATE CASCADE;
