    .ps-section-card.compact{
      padding:20px;
    }
      + '<div class="ps-create-page">'
      +   '<div class="ps-create-shell">'
      +     '<div class="ps-header-section">'
      +       '<h1 class="ps-header-title">Product Store</h1>'
      +       '<h2 class="ps-header-subtitle">Storefront &amp; orders</h2>'
      +       '<p class="ps-header-desc">Build merch, add-ons, and digital products that sell alongside tickets.</p>'
      +       '<div class="ps-nav-actions">'
      +         '<button class="ps-btn-primary" id="ps_create">Create product</button>'
      +         '<button class="ps-nav-btn" id="ps_orders">View orders</button>'
      +         '<button class="ps-nav-btn" id="ps_settings">Storefront settings</button>'
      +       '</div>'
      +     '<div id="ps_error_panel" class="ps-section-card" style="display:none;border:1px solid #f5c2c7;background:#fff5f5;">'
      +       '<div class="ps-section-title">Unable to load product store</div>'
      +       '<div class="ps-section-desc" id="ps_error_message" style="margin-bottom:16px;">We hit an error loading product store data.</div>'
      +       '<button class="ps-nav-btn" id="ps_retry">Retry</button>'
      +     '<div id="ps_cta" class="ps-section-card" style="display:none;">'
      +       '<div class="ps-section-title">Create your storefront</div>'
      +       '<div class="ps-section-desc">Add a slug, branding, and tax/fulfilment defaults to start selling products.</div>'
      +       '<button class="ps-btn-primary" id="ps_create_store">Set up storefront</button>'
      +     '<div class="ps-form-grid" id="ps_snapshot">'
      +       '<div class="ps-section-card">'
      +         '<div class="ps-form-label">Storefront URL</div>'
      +         '<div class="ps-section-title" style="font-size:20px;margin:0;" id="ps_storefront_url">—</div>'
      +         '<div class="ps-section-desc" style="margin-top:8px;" id="ps_storefront_status">Status: —</div>'
      +       '<div class="ps-section-card">'
      +         '<div class="ps-form-label">Product coverage</div>'
      +         '<div class="ps-section-title" style="font-size:20px;margin:0;" id="ps_product_counts">0 active products</div>'
      +         '<div class="ps-section-desc" style="margin-top:8px;" id="ps_product_counts_detail">0 drafts · 0 archived</div>'
      +       '<div class="ps-section-card">'
      +         '<div class="ps-form-label">Add-on attach rate</div>'
      +         '<div class="ps-section-title" style="font-size:20px;margin:0;" id="ps_attach_rate">0%</div>'
      +         '<div class="ps-section-desc" style="margin-top:8px;">Last 30 days</div>'
      +     '<div class="ps-form-grid">'
      +       '<div class="ps-section-card">'
      +         '<div class="ps-section-title">Product catalogue</div>'
      +         '<div class="ps-section-desc">Merch, add-ons, vouchers, digital, and donations.</div>'
      +         '<div class="ps-inline-row" style="margin:16px 0;">'
      +           '<input id="ps_search" class="ps-input" placeholder="Search products" />'
      +           '<button class="ps-inline-btn" id="ps_search_btn">Search</button>'
      +         '</div>'
      +         '<div class="table-list" id="ps_products_table">'
      +           '<div class="table-row head">'
      +             '<div>Product</div>'
      +             '<div>Category</div>'
      +             '<div>Fulfilment</div>'
      +             '<div>Inventory</div>'
      +             '<div>Status</div>'
      +           '</div>'
      +         '</div>'
      +       '</div>'
      +       '<div class="ps-section-card">'
      +         '<div class="ps-section-title">Checkout add-ons &amp; upsells</div>'
      +         '<div class="ps-section-desc">Attach products to shows, ticket types, or both.</div>'
      +         '<div class="ps-section-desc" style="margin-top:10px;">Manage rules in the upsells manager.</div>'
      +         '<button class="ps-nav-btn" id="ps_upsells" style="margin-top:16px;">Manage upsells</button>'
      +         '<div class="grid" style="margin-top:16px;" id="ps_top_products"></div>'
      +       '</div>'
      +     '<div class="ps-section-card" style="margin-top:24px;">'
      +       '<div class="ps-section-title">Orders &amp; fulfilment</div>'
      +       '<div class="ps-section-desc">Export CSV, track fulfilment status, and keep one order for tickets + products.</div>'
      +       '<button class="ps-nav-btn" id="ps_orders_footer" style="margin-top:16px;">View orders</button>'
      +       '<div class="ps-form-grid" style="margin-top:16px;">'
      +         '<div class="ps-section-card compact">'
      +           '<div class="ps-form-label">Revenue</div>'
      +           '<div class="ps-section-title" style="font-size:20px;margin:0;" id="ps_revenue_7d">£0.00 (7d)</div>'
      +           '<div class="ps-section-desc" style="margin-top:8px;" id="ps_revenue_month">£0.00 this month</div>'
      +         '</div>'
      +         '<div class="ps-section-card compact">'
      +           '<div class="ps-form-label">Stock alerts</div>'
      +           '<div class="ps-section-title" style="font-size:20px;margin:0;" id="ps_stock_alerts">0 low stock</div>'
      +           '<div class="ps-section-desc" style="margin-top:8px;" id="ps_stock_names">—</div>'
      +         '</div>'
      +       '</div>'
    if (top){
            return '<div class="ps-section-card compact"><div class="ps-section-title" style="font-size:18px;margin:0;">' + p.title + '</div><div class="ps-section-desc" style="margin-top:8px;">Revenue ' + money(p.revenuePence) + '</div></div>';
          }).join('') || '<div class="ps-section-desc">No upsells yet.</div>';
    + '<div class="ps-create-page">'
      +   '<div class="ps-create-shell">'
      +     '<div class="ps-header-section">'
      +       '<h1 class="ps-header-title">Storefront settings</h1>'
      +       '<h2 class="ps-header-subtitle">Branding &amp; fulfilment</h2>'
      +       '<p class="ps-header-desc">Manage your store slug, branding, and tax/fulfilment defaults.</p>'
      +     '</div>'
      +     '<div class="ps-section-card">'
      +       '<div class="ps-form-grid">'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Store name</span>'
      +           '<input id="ps_name" class="ps-input" placeholder="Store name" />'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Store slug</span>'
      +           '<input id="ps_slug" class="ps-input" placeholder="Store slug" />'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Logo URL</span>'
      +           '<input id="ps_logo" class="ps-input" placeholder="Logo URL" />'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Brand colour (hex)</span>'
      +           '<input id="ps_brand" class="ps-input" placeholder="Brand colour (hex)" />'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Support email</span>'
      +           '<input id="ps_support" class="ps-input" placeholder="Support email" />'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Policies / refund notes</span>'
      +           '<textarea id="ps_policies" class="ps-textarea" placeholder="Policies / refund notes"></textarea>'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Status</span>'
      +           '<select id="ps_status" class="ps-select">'
      +             '<option value="DRAFT">Draft</option>'
      +             '<option value="LIVE">Live</option>'
      +           '</select>'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Tax mode</span>'
      +           '<select id="ps_tax_mode" class="ps-select">'
      +             '<option value="NONE">No tax</option>'
      +             '<option value="VAT">VAT %</option>'
      +             '<option value="CUSTOM">Custom %</option>'
      +           '</select>'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Tax percent</span>'
      +           '<input id="ps_tax_percent" class="ps-input" placeholder="Tax percent" type="number" />'
      +         '</label>'
      +         '<label class="ps-checkbox"><input type="checkbox" id="ps_ship_enabled" /> Shipping enabled</label>'
      +         '<label class="ps-checkbox"><input type="checkbox" id="ps_collect_enabled" /> Collection enabled</label>'
      +         '<label class="ps-checkbox"><input type="checkbox" id="ps_digital_enabled" /> Digital enabled</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Shipping flat fee (pence)</span>'
      +           '<input id="ps_shipping_fee" class="ps-input" placeholder="Shipping flat fee (pence)" type="number" />'
      +         '</label>'
      +       '</div>'
      +       '<div class="ps-action-bar">'
      +         '<button class="ps-btn-primary" id="ps_settings_save">Save settings</button>'
      +         '<button class="ps-btn-cancel" id="ps_settings_back">Back</button>'
      +       '</div>'
      +       '<div class="ps-save-msg" id="ps_settings_msg"></div>'
      +     '</div>'
      + '<div class="ps-create-page">'
      +   '<div class="ps-create-shell">'
      +     '<div class="ps-header-section">'
      +       '<h1 class="ps-header-title">Product orders</h1>'
      +       '<h2 class="ps-header-subtitle">Orders &amp; fulfilment</h2>'
      +       '<p class="ps-header-desc">Track fulfilment and export data.</p>'
      +       '<div class="ps-nav-actions">'
      +         '<button class="ps-nav-btn" id="ps_orders_back">Back</button>'
      +       '</div>'
      +     '<div class="ps-section-card">'
      +       '<div class="table-list" id="ps_orders_table">'
      +         '<div class="table-row head">'
      +           '<div>Date</div>'
      +           '<div>Customer</div>'
      +           '<div>Source</div>'
      +           '<div>Total</div>'
      +           '<div>Fulfilment</div>'
      +         '</div>'
      +       '</div>'
      + '<div class="ps-create-page">'
      +   '<div class="ps-create-shell">'
      +     '<div class="ps-header-section">'
      +       '<h1 class="ps-header-title">Upsell rules</h1>'
      +       '<h2 class="ps-header-subtitle">Attach products to shows</h2>'
      +       '<p class="ps-header-desc">Attach products to shows and ticket types.</p>'
      +       '<div class="ps-nav-actions">'
      +         '<button class="ps-nav-btn" id="ps_upsells_back">Back</button>'
      +       '</div>'
      +     '</div>'
      +     '<div class="ps-section-card">'
      +       '<div class="ps-form-grid">'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Show</span>'
      +           '<select id="ps_upsell_show" class="ps-select"></select>'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Ticket type</span>'
      +           '<select id="ps_upsell_ticket" class="ps-select"></select>'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Product</span>'
      +           '<select id="ps_upsell_product" class="ps-select"></select>'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Variant</span>'
      +           '<select id="ps_upsell_variant" class="ps-select"></select>'
      +         '</label>'
      +         '<label class="ps-form-field">'
      +           '<span class="ps-form-label">Priority</span>'
      +           '<input id="ps_upsell_priority" class="ps-input" placeholder="Priority" type="number" value="1" />'
      +         '</label>'
      +         '<label class="ps-checkbox"><input type="checkbox" id="ps_upsell_recommended" checked /> Recommended</label>'
      +       '</div>'
      +       '<div class="ps-action-bar">'
      +         '<button class="ps-btn-primary" id="ps_upsell_add">Add rule</button>'
      +       '</div>'
      +       '<div id="ps_upsell_list" style="margin-top:24px;"></div>'
            + '<div class="ps-section-card compact" style="margin-bottom:12px;">'
            +   '<div class="ps-section-title" style="font-size:18px;margin:0;">' + rule.product.title + '</div>'
            +   '<div class="ps-section-desc" style="margin-top:8px;">Priority ' + rule.priority + ' · ' + (rule.active ? 'Active' : 'Inactive') + '</div>'
            +   '<button class="ps-nav-btn" data-delete="' + rule.id + '" style="margin-top:12px;">Delete</button>'
        }).join('') || '<div class="ps-section-desc">No rules yet.</div>';
