      +     '<div id="ps_error_panel" class="ps-section-card" style="display:none;border:1px solid #f5c2c7;background:#fff5f5;">'
      +       '<div class="ps-section-title">Unable to load product store</div>'
      +     '</div>'
      +     '<div class="ps-form-grid" id="ps_snapshot">'
      +       '<div class="ps-section-card">'
      +         '<div class="ps-form-label">Product coverage</div>'
      +       '</div>'
      +       '<div class="ps-section-card">'
      +     '</div>'
      +     '<div class="ps-form-grid">'
      +       '<div class="ps-section-card">'
